//! Contains the [`HitRecord`] structure, which stores data about ray-surface intersections.
//!
//! In a raytracer, when a ray intersects an object, we need to know more than just a boolean
//! "did it hit?". We need the exact coordinates of the intersection, the surface normal for
//! lighting calculations, texture coordinates, and the distance traveled.
//!
//! The [`HitRecord`] bundles all this crucial geometric information into a single,
//! easy-to-pass structure, decoupling the shape intersection logic from the shading logic.

use crate::functions::are_close;
use crate::geometry::{Normal, Point, Vec2D, is_close};
use crate::materials::Material;
use crate::ray::Ray;

/// A record of a successful ray-surface intersection.
///
/// This struct acts as a "payload" generated by objects implementing the `Shape` trait
/// when they are hit by a [`Ray`]. It contains all the geometric data necessary for
/// subsequent shading, texturing, and recursive ray bouncing.
///
/// # Examples
///
/// ```rust,no_run
/// # use rstrace::hit_record::HitRecord;
/// # use rstrace::geometry::{Point, Normal, Vec2D, Vector};
/// # use rstrace::ray::Ray;
/// let incident_ray = Ray::new(Point::new(0.0, 0.0, 0.0), Vector::new(0.0, 0.0, 1.0));
///
/// let record = HitRecord {
///     world_point: Point::new(0.0, 0.0, 5.0),
///     normal: Normal::new(0.0, 0.0, -1.0),
///     uv: Vec2D::new(0.5, 0.5),
///     t: 5.0,
///     ray: incident_ray,
/// };
/// ```
pub struct HitRecord<'a> {
    /// The precise 3D position in world space where the intersection occurred.
    pub world_point: Point,

    /// The surface normal vector at the point of intersection.
    /// Crucial for calculating reflections, refractions, and lighting.
    pub normal: Normal,

    /// The 2D surface coordinates (u, v) at the intersection point.
    /// Used for mapping 2D textures or procedural patterns onto 3D objects.
    pub uv: Vec2D,

    /// The scalar parameter `t` such that `ray.origin + t * ray.direction == world_point`.
    /// Represents the distance (or "time") traveled along the ray.
    pub t: f32,

    /// The incident light ray that caused this intersection.
    pub ray: Ray,

    /// The hit material.
    pub material: &'a Material,
}

impl<'a> HitRecord<'a> {
    /// Checks if two `HitRecord` instances are approximately equal.
    ///
    /// Due to floating-point inaccuracies inherent in raytracing mathematics,
    /// exact equality (`==`) is often unreliable. This method compares all fields
    /// (point, normal, uv, t, and ray) using a small epsilon tolerance.
    ///
    /// This is primarily used in unit testing to verify intersection algorithms.
    ///
    /// # Arguments
    ///
    /// * `hr` - A reference to the other `HitRecord` to compare against.
    pub fn is_close(&self, hr: &HitRecord) -> bool {
        is_close(self.world_point, hr.world_point)
            && is_close(self.normal, hr.normal)
            && are_close(self.t, hr.t)
            && self.uv.is_close(&hr.uv)
            && self.ray.is_close(hr.ray)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::brdf::DiffusiveBrdf;
    use crate::color::Color;
    use crate::geometry::{Point, Vec2D, Vector};
    use crate::pigments::CheckeredPigment;

    fn material() -> Material {
        Material {
            pigment: Box::new(CheckeredPigment {
                color1: Color::new(0.0, 1.0, 2.0),
                color2: Color::new(3.0, 4.0, 5.0),
                steps: 5,
            }),
            brdf: Box::new(DiffusiveBrdf {}),
            emitted_radiance: Box::new(CheckeredPigment {
                color1: Color::new(0.0, 1.0, 2.0),
                color2: Color::new(3.0, 4.0, 5.0),
                steps: 5,
            }),
        }
    }

    #[test]
    fn test_is_close() {
        let ray = Ray::new(Point::new(0.0, 1.0, -1.0), Vector::new(0.0, 0.0, 0.0));
        let mat1 = material();
        let mut hr1 = HitRecord {
            world_point: Point::new(1.0, 2.0, 3.0),
            normal: Normal::new(4.0, 5.0, 6.0),
            uv: Vec2D::new(7.0, 8.0),
            t: 1.0,
            ray,
            material: &mat1,
        };
        let ray2 = Ray::new(
            Point::new(0.0000001, 1.0, -0.999999),
            Vector::new(0.0000001, 0.0, -0.0000001),
        );
        let mat2 = material();
        let mut hr2 = HitRecord {
            world_point: Point::new(1.0, 1.999999, 3.0),
            normal: Normal::new(4.0000001, 5.0, 6.0),
            uv: Vec2D::new(7.0, 8.0000001),
            t: 1.0000001,
            ray: ray2,
            material: &mat2,
        };
        assert!(hr1.is_close(&hr2));

        hr2.t = 0.0001;
        assert!(!hr1.is_close(&hr2));

        hr1.t = 0.0001; // Make it equal
        hr2.normal = Normal::new(4.001, 5.0, 6.0);
        assert!(!hr1.is_close(&hr2));

        hr1.normal = Normal::new(4.001, 5.0, 6.0); // Make it equal
        hr2.world_point = Point::new(1.0, 2.001, 3.0);
        assert!(!hr1.is_close(&hr2));

        hr1.world_point = Point::new(1.0, 2.001, 3.0);
        hr2.uv = Vec2D::new(7.0, 7.9999);
        assert!(!hr1.is_close(&hr2));

        hr1.uv = Vec2D::new(7.0, 7.9999);
        hr2.ray = Ray::new(Point::new(0.0, 1.0001, -1.0), Vector::new(0.0, 0.0, 0.0));
        assert!(!hr1.is_close(&hr2));

        hr1.ray = Ray::new(Point::new(0.0, 1.0001, -1.0), Vector::new(0.0, 0.0, 0.0));
        hr2.ray = Ray::new(Point::new(0.0, 1.0001, -1.0), Vector::new(0.0, 0.0, 0.0001));
        assert!(!hr1.is_close(&hr2));
    }
}
